### ISSUE TITLE
当前上下文中不存在名称“cgStat”

### ISSUE THREAD

**Issue by jinxiu0406** [Zolo-mario/zlua#1]
你好，我想学习你的程序，不过编译失败。

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0103	当前上下文中不存在名称“cgStat”	zlua	    \zlua-master\projects\zlua\Compiler\CodeGenerator.cs	40	活动

`        void cgBlock(funcInfo fi, blockContext node)
        {
            foreach (var item in node.StatStar) {
                cgStat(fi, item);
            }
            if (node.RetStatOptional != null) {
                cgRetStat(fi, node.RetStatOptional);
            }
        }`

**Comment by Zolo-mario** [comment]
你好，zlua正在开发中，因此没有编译通过

你姑且可以下载zlua的v0.1 Release版，那是我半年前写的，能编译通过，但是有一些运行时错误没有解决

或者你可以查看zlua_prototype项目，那是使用python写的原型，是zlua的基础

另外，现在我正在重写这个项目，因此将会和v0.1 Release版差距很大
